version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - "8000:8000"   # GraphQL HTTP
      - "8001:8001"   # GraphQL WS
      - "8020:8020"   # admin / deploy
      - "8030:8030"   # subgraph indexing status
      - "8040:8040"   # Prometheus
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "quai:https://rpc.quai.network/cyprus1"
      GRAPH_LOG: info
  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - "5001:5001"
    volumes:
      - ipfs-data:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  ipfs-data:
  postgres-data:
